# Dockerfile.backend

FROM python:3.10-slim

# Copy backend code
WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY backend/ /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Flask app
CMD ["python3", "flask_app.py"]