# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /app

# Copy backend code
COPY requirements.txt /app/requirements.txt
COPY backend/ /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Flask app
CMD ["sh", "-c", "python3 init.py && python3 flask_app.py"]